services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "4200:4200"
      - "5000:5000"
    depends_on:
      - emongo

  webapi:
    build:
      context: ./javaapi
    container_name: webapi
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - emartdb

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
      - webapi

  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
    ports:
      - "3306:3306"

